[package]
name = "oauth10a"
description = "A rust implementation of the oauth 1.0a protocol fully-async with logging, metrics and tracing facilities"
version = "1.3.19"
edition = "2021"
rust-version = "1.60.0"
authors = ["Florentin Dubois <florentin.dubois@clever-cloud.com>"]
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/CleverCloud/oauth10a-rust"
keywords = [
    "clevercloud",
    "client",
    "logging",
    "metrics",
    "oauth1a",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { version = "^0.1.68", optional = true }
base64 = { version = "^0.21.0", optional = true }
bytes = { version = "^1.4.0", features = ["serde"], optional = true }
cidr = { version = "^0.2.1", optional = true }
crypto-common = { version = "^0.1.6", optional = true }
headers = { version = "^0.3.8", optional = true }
hmac = { version = "^0.12.1", features = ["std"], optional = true }
hyper = { version = "^0.14.26", default-features = false, optional = true }
hyper-tls = { version = "^0.5.0", optional = true }
hyper-proxy = { version = "^0.9.1", default-features = false, features = ["tls"], optional = true }
once_cell = { version = "^1.17.1", optional = true }
log = { version = "^0.4.17", optional = true }
prometheus = { version = "^0.13.3", optional = true }
serde = { version = "^1.0.163", features = ["derive"], optional = true }
serde_json = { version = "^1.0.96", features = [
    "preserve_order",
    "float_roundtrip",
], optional = true }
sha2 = { version = "^0.10.6", optional = true }
thiserror = { version = "^1.0.40", optional = true }
tracing = { version = "^0.1.37", optional = true }
tracing-futures = { version = "^0.2.5", optional = true }
url = { version = "^2.3.1", default-features = false, features = ["serde"], optional = true }
urlencoding = { version = "^2.1.2", optional = true }
uuid = { version = "^1.3.3", features = ["serde", "v4"], optional = true }

[features]
default = ["client", "proxy", "logging"]
client = [
    "async-trait",
    "base64",
    "bytes",
    "crypto-common",
    "hmac",
    "hyper",
    "hyper/client",
    "hyper/tcp",
    "hyper/http1",
    "hyper-tls",
    "serde",
    "serde_json",
    "sha2",
    "thiserror",
    "urlencoding",
    "uuid",
]
logging = ["log", "tracing/log-always"]
trace = ["tracing", "tracing-futures"]
tokio = ["tracing-futures/tokio"]
metrics = ["once_cell", "prometheus"]
proxy = ["cidr", "headers", "hyper-proxy", "url"]
